function depthViewerGUI()

W = 600;
H = 110;
rH = 20;
rW = 600-2*rH;

D = dir('*.h5');  % or jpeg or whatever.
h.NAM = {D(:).name};  % Store the name of all items returned in D.
h.f = figure('units','pixels',...
    'position',[0 0 W H],...
    'menubar','none',...
    'name','Verify Password.',...
    'resize','off',...
    'numbertitle','off',...
    'name','Run Depth');


%run
h.pb = uicontrol('style','push',...
    'units','pix',...
    'position',[10 10 rW 2*rH],...
    'HorizontalAlign','left',...
    'string','Run',...
    'fontsize',12,'fontweight','bold',...
    'callback',@run_callback);

%edit input
in_p_pos = [h.pb.Position(1)  h.pb.Position(2)+h.pb.Position(4)+5 rW rH+5] ;
h.input.p = uipanel('Parent',h.f,...
        'units','pixels','fontsize',10,...
        'Position',in_p_pos,'borderType','none');
    
p = [1  5 in_p_pos(3)-rH-5-1 rH] ;
h.input.edit =  uicontrol('parent',h.input.p,'style','edit',...
    'units','pix',...
    'position',p,...
    'HorizontalAlign','left',...
    'string','C:\');


p = [h.input.edit.Position(1)+h.input.edit.Position(3)+5   h.input.edit.Position(2)  rH rH];
uicontrol('style','pushbutton','parent',h.input.p,'units','pixels',...
        'pos',p,'string','...',...
        'callback',@callback_selectInputFile);


%checkboxes
h.viewr = uicontrol('style','checkbox',...
    'units','pix',...
    'position',[h.input.p.Position(1) h.input.p.Position(2)+h.input.p.Position(4)+5 100 rH],...
    'string','view restults',...
    'HorizontalAlign','left',...
    'Value',1);

h.saver = uicontrol('style','checkbox',...
    'units','pix',...
    'position',[h.viewr.Position(1)+h.viewr.Position(3)+5 h.viewr.Position(2) 100 rH],...
    'string','save results',...
    'HorizontalAlign','left',...
    'Value',1);

movegui(h.f,'center');
guidata(h.f,h);
end

function callback_selectInputFile(varargin)
h = guidata(varargin{1});

    [fname,folder] = uigetfile(...
    {'*.h5;*.ivlpi',...
    'IV2 Files (*.h5,*.ivlpi)'; ...
    '*.h5',  'Scope file (*.h5)'; ...
    '*.ivlpi','Pipe file (*.ivlpi)'}, ...
    'Pick a file',h.input.edit.String);

h.input.edit.String = fullfile(folder,fname);

guidata(h.f,h);
end


function run_callback(varargin)
h = guidata(varargin{1});
viewResults = h.viewr.Value;
saveResults = h.saver.Value;

Pipe.autopipe(h.input.edit.String,'saveOutput',saveResults,'viewResults',viewResults);
end