if isempty(strfind(version, 'R2017a')) %#ok
    error('build_IV2calibTool() must be ran with Matlab R2017a!');
end

%for non FG, just replace the function and output names

outputFolder = '\\ger\ec\proj\ha\RSG\SA_3DCam\Algorithm\Share\CaptureLoopFG';
mkdirSafe(outputFolder);
cmd = sprintf([
    'mcc -m Iv2CaptureLoopFG.m ' ...
    '-d  %s '...
    '-a +Pipe\\tables\\* '...
    '-a +Calibration\\targets\\* '...
    '-a +Calibration\\releaseConfigCalibL520\\* '...
    '-a +Calibration\\releaseConfigCalibVGA\\* '...
    '-a +Calibration\\releaseConfigCalibXGA\\* '...
    '-a +Calibration\\releaseConfigCalib360p\\* '...
    '-a @HWinterface\\IVCam20Device\\* '...
    '-a @HWinterface\\presetScripts\\* '...
    ],outputFolder);
eval(cmd);

