/*****************************************************************************
    C++ RTL Simulation Model
    
    Generated at: 16:25:18 IDT (+0300), Wednesday 05 April 2017
    Generated on: icsl2290
    Generated by: ygelbfis (yoni.gelbfish,11224754)
    
    Created by: CellMath Designer 2015.1.03 
    Copyright (c) 2014-2015 Cadence Design Systems. All rights reserved worldwide.
    
    Cadence Design Systems proprietary and confidential
    ===================================================
    
    May contain information that incorporates Cadence Design Systems CellMath
    and other inventions claimed in Pending U.S. Patents.
    
    May contain Cadence Design Systems Trade Secrets of which use, disclosure or
    reproduction is contractually restricted or prohibited.  For more
    information, contact your legal department before any use, disclosure or
    reproduction.
*******************************************************************************/
#include "systemc.h"
#if !defined(systemc_beh_c2_libs)
#define systemc_beh_c2_libs
template <class T>
static inline
void
c2_sqrt(
    T &q,       // quotient output
    T &r,       // remainder output
    const T &x, // input
    int bits=0  // max number of bits in x to consider
)
{
    q=T(0);
    r=x;

    int stages = bits ? bits/2+(bits&1) : sizeof(T)*8/2;
    for (int i=stages-1; i>=0; i--) {
        T d=(q<<(i+1)) | (T(1)<<(2*i));
        if (r >= d) {
            r -= d;
            q |= T(1)<<i;
        }
    }
}

#endif // !defined(systemc_beh_c2_libs)
    // !!!! amethyst/writers/SystemCbeh.cpp:4013
#if !defined cynw_cm_float_rsq_E8_M23_INCLUDED
#define cynw_cm_float_rsq_E8_M23_INCLUDED

struct class_cynw_cm_float_rsq_E8_M23 { // BDW_REPLACE_NAME cynw_cm_float_rsq

    // Work around for SystemC 2.2 not having a signature
    // to a concatenation by an int.
#   if SYSTEMC_VERSION > 20060000 && SYSTEMC_VERSION < 20091210
        typedef unsigned long shift_v;
#   else
        typedef unsigned int shift_v;
#   endif

    void operator () (
    const sc_uint<1>& a_sign // input  a_sign : unsigned
    ,const sc_uint<8>& a_exp // input  a_exp[7:0] : unsigned
    ,const sc_uint<23>& a_man // input  a_man[22:0] : unsigned
    ,sc_uint<32>& x // output  x[31:0] : unsigned
)
{


// Signal initializations:

    inst_cellmath__16=0;
    inst_cellmath__17=0;
    inst_cellmath__18=0;
    inst_cellmath__20=0;
    inst_cellmath__22=0;
    inst_cellmath__24=0;
    inst_cellmath__25=0;
    inst_cellmath__26=0;
    inst_cellmath__29=0;
    inst_cellmath__30=0;
    inst_cellmath__31=0;
    inst_cellmath__33=0;
    inst_cellmath__35=0;
    inst_cellmath__37=0;
    inst_cellmath__60=0;
    inst_mult_d_cellmath__64=0;
    inst_FP_RSQ_MULT_C_mult_c_datapath_prodSum=0;
    inst_FP_RSQ_MULT_B_mult_b_datapath_prodSum=0;
    inst_cellmath__72=0;
    inst_cellmath__74=0;
    inst_cellmath__80=0;
    inst_cellmath__22__7=0;
    inst_cellmath__22__6=0;
    inst_cellmath__22__8=0;
    inst_cellmath__22__4=0;
    inst_cellmath__26__9=0;
    inst_cellmath__30__14=0;
    inst_cellmath__31__15=0;
    inst_cellmath__33__23=0;
    inst_mult_d_cellmath__64__29=0;
    inst_mult_d_cellmath__64__28=0;
    inst_mult_d_cellmath__64__30=0;
    inst_mult_d_cellmath__64__27=0;
    inst_mult_d_cellmath__64__34=0;
    inst_mult_d_cellmath__64__33=0;
    inst_mult_d_cellmath__64__35=0;
    inst_mult_d_cellmath__64__32=0;
    inst_mult_d_cellmath__64__39=0;
    inst_mult_d_cellmath__64__38=0;
    inst_mult_d_cellmath__64__40=0;
    inst_mult_d_cellmath__64__37=0;
    inst_mult_d_cellmath__64__44=0;
    inst_mult_d_cellmath__64__43=0;
    inst_mult_d_cellmath__64__45=0;
    inst_mult_d_cellmath__64__42=0;
    inst_mult_d_cellmath__64__49=0;
    inst_mult_d_cellmath__64__48=0;
    inst_mult_d_cellmath__64__50=0;
    inst_mult_d_cellmath__64__47=0;
    inst_mult_d_cellmath__64__54=0;
    inst_mult_d_cellmath__64__53=0;
    inst_mult_d_cellmath__64__55=0;
    inst_mult_d_cellmath__64__52=0;
    inst_mult_d_cellmath__64__59=0;
    inst_mult_d_cellmath__64__58=0;
    inst_mult_d_cellmath__64__60=0;
    inst_mult_d_cellmath__64__57=0;
    inst_mult_d_cellmath__64__64=0;
    inst_mult_d_cellmath__64__63=0;
    inst_mult_d_cellmath__64__65=0;
    inst_mult_d_cellmath__64__62=0;
    inst_mult_d_cellmath__64__69=0;
    inst_mult_d_cellmath__64__68=0;
    inst_mult_d_cellmath__64__70=0;
    inst_mult_d_cellmath__64__67=0;
    inst_mult_d_cellmath__64__74=0;
    inst_mult_d_cellmath__64__73=0;
    inst_mult_d_cellmath__64__75=0;
    inst_mult_d_cellmath__64__72=0;
    inst_mult_d_cellmath__64__79=0;
    inst_mult_d_cellmath__64__78=0;
    inst_mult_d_cellmath__64__80=0;
    inst_mult_d_cellmath__64__77=0;
    inst_mult_d_cellmath__64__84=0;
    inst_mult_d_cellmath__64__83=0;
    inst_mult_d_cellmath__64__85=0;
    inst_mult_d_cellmath__64__82=0;
    inst_mult_d_cellmath__64__89=0;
    inst_mult_d_cellmath__64__88=0;
    inst_mult_d_cellmath__64__90=0;
    inst_mult_d_cellmath__64__87=0;
    inst_mult_d_cellmath__64__94=0;
    inst_mult_d_cellmath__64__93=0;
    inst_mult_d_cellmath__64__92=0;
    inst_cellmath__74__103=0;
    inst_cellmath__74__106=0;
    inst_cellmath__74__105=0;
    inst_cellmath__32_0=0;
    inst_cellmath__33__23_0=0;
    inst_cellmath__29_0=0;
    inst_cellmath__59_0=0;
    tmp_0_23_17_=0;


// Default output values:

    x=0;
    // !!!! amethyst/writers/SystemCbeh.cpp:5364

    // !!!! amethyst/writers/SystemCbeh.cpp:4767
    // Compare anchor: tmp_0_23_17_
    tmp_0_23_17_ = 
        (a_exp(0,0),a_man(22,17))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:2912
    // !!!! amethyst/writers/SystemCbeh.cpp:3086
        sc_uint<13> inst_cellmath__17_tmp_0 = 
            -((sc_uint<13>)(a_exp))
            +((sc_uint<13>)(sc_uint<9>("0bus011111110")));
        inst_cellmath__17 = (((sc_uint<1>)inst_cellmath__17_tmp_0.and_reduce())==((sc_uint<1>)1))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:2912
    // !!!! amethyst/writers/SystemCbeh.cpp:3086
        sc_uint<27> inst_cellmath__18_tmp_1 = 
            -((sc_uint<27>)(a_man))
            -((sc_uint<27>)(sc_uint<2>("0b01")));
        inst_cellmath__18 = (((sc_uint<1>)inst_cellmath__18_tmp_1.and_reduce())==((sc_uint<1>)1))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:3332
    // Compare anchor: inst_cellmath__25
    inst_cellmath__25 = 
        
            ((sc_uint<1>)((sc_uint<1>)(inst_cellmath__17)))
            &((sc_uint<1>)(~(sc_uint<1>)(inst_cellmath__18)))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:3332
    // Compare anchor: inst_cellmath__29
    inst_cellmath__29 = 
        
            ((sc_uint<1>)((sc_uint<1>)(inst_cellmath__25)))
            |((sc_uint<1>)((sc_uint<1>)(a_sign)))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:2912
    // !!!! amethyst/writers/SystemCbeh.cpp:3086
        sc_uint<12> inst_cellmath__16_tmp_2 = 
            -((sc_uint<12>)(a_exp))
            -((sc_uint<12>)(sc_uint<2>("0b01")));
        inst_cellmath__16 = (((sc_uint<1>)inst_cellmath__16_tmp_2.and_reduce())==((sc_uint<1>)1))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:4536
    // Compare anchor: inst_cellmath__22__7
    inst_cellmath__22__7 = 
        ~(sc_uint<1>)(a_exp(0,0))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:2912
    sc_uint<9> inst_cellmath__22__6_tmp_3;
    // !!!! amethyst/writers/SystemCbeh.cpp:2912
    // !!!! amethyst/writers/SystemCbeh.cpp:3086
    // Compare anchor: inst_cellmath__22__6_tmp_3
    inst_cellmath__22__6_tmp_3 = 
        
            -((sc_uint<9>)(inst_cellmath__22__7))
            -((sc_uint<9>)(a_exp))
    ;
    // !!!! amethyst/writers/SystemCbeh.cpp:3086
    // Compare anchor: inst_cellmath__22__6
    inst_cellmath__22__6 = 
        inst_cellmath__22__6_tmp_3
            +((sc_uint<9>)(sc_uint<8>("0bus01111111")))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:3332
    // Compare anchor: inst_cellmath__22__8
    inst_cellmath__22__8 = 
        
            ((sc_uint<1>)(~(sc_uint<1>)(inst_cellmath__18)))
            &((sc_uint<1>)((sc_uint<1>)(a_exp(0,0))))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:2912
    // !!!! amethyst/writers/SystemCbeh.cpp:3086
        sc_uint<13> inst_cellmath__26__9_tmp_4 = 
            -((sc_uint<13>)(( ((sc_uint<5>)(sc_int<1>)(inst_cellmath__22__6(8,8))), inst_cellmath__22__6(8,1))))
            +((sc_uint<13>)(inst_cellmath__22__8))
            +((sc_uint<13>)(sc_uint<8>("0bus01111111")));
        inst_cellmath__26__9 = (((sc_uint<1>)(inst_cellmath__26__9_tmp_4(12,12)))==((sc_uint<1>)1))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:3332
    // Compare anchor: inst_cellmath__26
    inst_cellmath__26 = 
        
            ((sc_uint<1>)((sc_uint<1>)(inst_cellmath__26__9)))
            &((sc_uint<1>)(~(sc_uint<1>)(inst_cellmath__17)))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:3332
    // Compare anchor: inst_cellmath__31__15
    inst_cellmath__31__15 = 
        
            ((sc_uint<1>)((sc_uint<1>)(inst_cellmath__16)))
            |((sc_uint<1>)((sc_uint<1>)(inst_cellmath__26)))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:3332
    // Compare anchor: inst_cellmath__31
    inst_cellmath__31 = 
        
            ((sc_uint<1>)(~(sc_uint<1>)(inst_cellmath__29)))
            &((sc_uint<1>)((sc_uint<1>)(inst_cellmath__31__15)))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:3332
    // Compare anchor: inst_cellmath__33__23
    inst_cellmath__33__23 = 
        
            ((sc_uint<1>)((sc_uint<1>)(inst_cellmath__29)))
            |((sc_uint<1>)((sc_uint<1>)(inst_cellmath__31)))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:3332
    // Compare anchor: inst_cellmath__24
    inst_cellmath__24 = 
        
            ((sc_uint<1>)((sc_uint<1>)(inst_cellmath__17)))
            &((sc_uint<1>)((sc_uint<1>)(inst_cellmath__18)))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:2912
    // !!!! amethyst/writers/SystemCbeh.cpp:3086
        sc_uint<13> inst_cellmath__22__4_tmp_5 = 
            -((sc_uint<13>)(inst_cellmath__22__8))
            +((sc_uint<13>)(( ((sc_uint<5>)(sc_int<1>)(inst_cellmath__22__6(8,8))), inst_cellmath__22__6(8,1))))
            +((sc_uint<13>)(sc_uint<8>("0bus01111110")));
        inst_cellmath__22__4 = (((sc_uint<1>)(inst_cellmath__22__4_tmp_5(12,12)))==((sc_uint<1>)1))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:3332
    // Compare anchor: inst_cellmath__22
    inst_cellmath__22 = 
        
            ((sc_uint<1>)((sc_uint<1>)(inst_cellmath__22__4)))
            &((sc_uint<1>)(~(sc_uint<1>)(inst_cellmath__17)))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:3332
    // Compare anchor: inst_cellmath__30__14
    inst_cellmath__30__14 = 
        
            ((sc_uint<1>)((sc_uint<1>)(inst_cellmath__24)))
            |((sc_uint<1>)((sc_uint<1>)(inst_cellmath__22)))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:3332
    // Compare anchor: inst_cellmath__30
    inst_cellmath__30 = 
        
            ((sc_uint<1>)(~(sc_uint<1>)(inst_cellmath__29)))
            &((sc_uint<1>)((sc_uint<1>)(inst_cellmath__30__14)))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:4767
    // Compare anchor: inst_cellmath__33__23_0
    inst_cellmath__33__23_0 = 
        (inst_cellmath__33__23,inst_cellmath__30)
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:2912
    sc_uint<9> inst_cellmath__32_0_tmp_6;
    // !!!! amethyst/writers/SystemCbeh.cpp:2912
    sc_uint<9> inst_cellmath__32_0_tmp_7;
    // !!!! amethyst/writers/SystemCbeh.cpp:2912
    // !!!! amethyst/writers/SystemCbeh.cpp:3086
    // Compare anchor: inst_cellmath__32_0_tmp_7
    inst_cellmath__32_0_tmp_7 = 
        
            -((sc_uint<9>)(((sc_uint<9>)((inst_cellmath__22__8)<<(shift_v)1))))
            -((sc_uint<9>)(inst_cellmath__22__7))
    ;
    // !!!! amethyst/writers/SystemCbeh.cpp:3086
    // Compare anchor: inst_cellmath__32_0_tmp_6
    inst_cellmath__32_0_tmp_6 = 
        inst_cellmath__32_0_tmp_7
            -((sc_uint<9>)(a_exp))
    ;
    // !!!! amethyst/writers/SystemCbeh.cpp:3086
    // Compare anchor: inst_cellmath__32_0
    inst_cellmath__32_0 = 
        inst_cellmath__32_0_tmp_6
            +((sc_uint<9>)(sc_uint<9>("0bus101111101")))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:2018
    // !!!! amethyst/writers/SystemCbeh.cpp:2041
    // Compare anchor: inst_cellmath__33
    inst_cellmath__33 = 
        
        -(int)((sc_uint<2>)inst_cellmath__33__23_0 == sc_uint<2>("0bus00")) & ((sc_uint<8>)(inst_cellmath__32_0(8,1))) |
        -(int)((sc_uint<1>)inst_cellmath__33__23_0(1,1) == sc_uint<1>("0bus1")) & ((sc_uint<8>)(sc_uint<8>("0bus11111111")))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:3332
    // Compare anchor: inst_cellmath__74__106
    inst_cellmath__74__106 = 
        
            ((sc_uint<1>)((sc_uint<1>)(inst_cellmath__18)))
            &((sc_uint<1>)((sc_uint<1>)(a_exp(0,0))))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:3332
    // Compare anchor: inst_cellmath__74__105
    inst_cellmath__74__105 = 
        
            ((sc_uint<1>)((sc_uint<1>)(inst_cellmath__74__106)))
            |((sc_uint<1>)((sc_uint<1>)(inst_cellmath__30)))
            |((sc_uint<1>)((sc_uint<1>)(inst_cellmath__31)))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:2912
    // !!!! amethyst/writers/SystemCbeh.cpp:3086
        sc_uint<28> inst_cellmath__20_tmp_8 = 
            -((sc_uint<28>)(a_man))
            +((sc_uint<28>)(sc_uint<24>("0bus011111111111111111111110")));
        inst_cellmath__20 = (((sc_uint<1>)(inst_cellmath__20_tmp_8(27,27)))==((sc_uint<1>)1))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:3332
    // Compare anchor: inst_cellmath__74__103
    inst_cellmath__74__103 = 
        
            ((sc_uint<1>)((sc_uint<1>)(inst_cellmath__20)))
            &((sc_uint<1>)(~(sc_uint<1>)(a_exp(0,0))))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:4767
    // Compare anchor: inst_cellmath__29_0
    inst_cellmath__29_0 = 
        (inst_cellmath__29,inst_cellmath__74__105,inst_cellmath__74__103)
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:4536
    // Compare anchor: inst_cellmath__35
    inst_cellmath__35 = 
        ~(sc_uint<1>)(a_man(16,16))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:3332
    // Compare anchor: inst_mult_d_cellmath__64__94(0,0)
    inst_mult_d_cellmath__64__94(0,0) = 
        
            ((sc_uint<1>)((sc_uint<1>)(a_man(15,15))))
            &((sc_uint<1>)((sc_uint<1>)(inst_cellmath__35)))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:4536
    // Compare anchor: inst_mult_d_cellmath__64__93(0,0)
    inst_mult_d_cellmath__64__93(0,0) = 
        ~(sc_uint<1>)(inst_mult_d_cellmath__64__94(0,0))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:4767
    // Compare anchor: inst_mult_d_cellmath__64__92
    inst_mult_d_cellmath__64__92 = 
        (inst_mult_d_cellmath__64__93(0,0),sc_uint<1>(0),a_man(15,15))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:3332
    // Compare anchor: inst_mult_d_cellmath__64__89(0,0)
    inst_mult_d_cellmath__64__89(0,0) = 
        
            ((sc_uint<1>)((sc_uint<1>)(a_man(14,14))))
            &((sc_uint<1>)((sc_uint<1>)(inst_cellmath__35)))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:4536
    // Compare anchor: inst_mult_d_cellmath__64__88(0,0)
    inst_mult_d_cellmath__64__88(0,0) = 
        ~(sc_uint<1>)(inst_mult_d_cellmath__64__89(0,0))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:3332
    // Compare anchor: inst_mult_d_cellmath__64__90
    inst_mult_d_cellmath__64__90 = 
        
            ((sc_uint<1>)((sc_uint<1>)(a_man(14,14))))
            &((sc_uint<1>)((sc_uint<1>)(a_man(15,15))))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:4767
    // Compare anchor: inst_mult_d_cellmath__64__87
    inst_mult_d_cellmath__64__87 = 
        (inst_mult_d_cellmath__64__88(0,0),inst_mult_d_cellmath__64__90,sc_uint<1>(0),a_man(14,14))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:3332
    // Compare anchor: inst_mult_d_cellmath__64__84(0,0)
    inst_mult_d_cellmath__64__84(0,0) = 
        
            ((sc_uint<1>)((sc_uint<1>)(a_man(13,13))))
            &((sc_uint<1>)((sc_uint<1>)(inst_cellmath__35)))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:4536
    // Compare anchor: inst_mult_d_cellmath__64__83(0,0)
    inst_mult_d_cellmath__64__83(0,0) = 
        ~(sc_uint<1>)(inst_mult_d_cellmath__64__84(0,0))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:2018
    // !!!! amethyst/writers/SystemCbeh.cpp:2041
    // Compare anchor: inst_mult_d_cellmath__64__85
    inst_mult_d_cellmath__64__85 = 
        
        -(int)((sc_uint<1>)a_man(13,13) == sc_uint<1>("0bus1")) & ((sc_uint<2>)(a_man(15,14)))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:4767
    // Compare anchor: inst_mult_d_cellmath__64__82
    inst_mult_d_cellmath__64__82 = 
        (inst_mult_d_cellmath__64__83(0,0),inst_mult_d_cellmath__64__85,sc_uint<1>(0),a_man(13,13))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:3332
    // Compare anchor: inst_mult_d_cellmath__64__79(0,0)
    inst_mult_d_cellmath__64__79(0,0) = 
        
            ((sc_uint<1>)((sc_uint<1>)(a_man(12,12))))
            &((sc_uint<1>)((sc_uint<1>)(inst_cellmath__35)))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:4536
    // Compare anchor: inst_mult_d_cellmath__64__78(0,0)
    inst_mult_d_cellmath__64__78(0,0) = 
        ~(sc_uint<1>)(inst_mult_d_cellmath__64__79(0,0))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:2018
    // !!!! amethyst/writers/SystemCbeh.cpp:2041
    // Compare anchor: inst_mult_d_cellmath__64__80
    inst_mult_d_cellmath__64__80 = 
        
        -(int)((sc_uint<1>)a_man(12,12) == sc_uint<1>("0bus1")) & ((sc_uint<3>)(a_man(15,13)))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:4767
    // Compare anchor: inst_mult_d_cellmath__64__77
    inst_mult_d_cellmath__64__77 = 
        (inst_mult_d_cellmath__64__78(0,0),inst_mult_d_cellmath__64__80,sc_uint<1>(0),a_man(12,12))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:3332
    // Compare anchor: inst_mult_d_cellmath__64__74(0,0)
    inst_mult_d_cellmath__64__74(0,0) = 
        
            ((sc_uint<1>)((sc_uint<1>)(a_man(11,11))))
            &((sc_uint<1>)((sc_uint<1>)(inst_cellmath__35)))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:4536
    // Compare anchor: inst_mult_d_cellmath__64__73(0,0)
    inst_mult_d_cellmath__64__73(0,0) = 
        ~(sc_uint<1>)(inst_mult_d_cellmath__64__74(0,0))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:2018
    // !!!! amethyst/writers/SystemCbeh.cpp:2041
    // Compare anchor: inst_mult_d_cellmath__64__75
    inst_mult_d_cellmath__64__75 = 
        
        -(int)((sc_uint<1>)a_man(11,11) == sc_uint<1>("0bus1")) & ((sc_uint<4>)(a_man(15,12)))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:4767
    // Compare anchor: inst_mult_d_cellmath__64__72
    inst_mult_d_cellmath__64__72 = 
        (inst_mult_d_cellmath__64__73(0,0),inst_mult_d_cellmath__64__75,sc_uint<1>(0),a_man(11,11))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:3332
    // Compare anchor: inst_mult_d_cellmath__64__69(0,0)
    inst_mult_d_cellmath__64__69(0,0) = 
        
            ((sc_uint<1>)((sc_uint<1>)(a_man(10,10))))
            &((sc_uint<1>)((sc_uint<1>)(inst_cellmath__35)))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:4536
    // Compare anchor: inst_mult_d_cellmath__64__68(0,0)
    inst_mult_d_cellmath__64__68(0,0) = 
        ~(sc_uint<1>)(inst_mult_d_cellmath__64__69(0,0))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:2018
    // !!!! amethyst/writers/SystemCbeh.cpp:2041
    // Compare anchor: inst_mult_d_cellmath__64__70
    inst_mult_d_cellmath__64__70 = 
        
        -(int)((sc_uint<1>)a_man(10,10) == sc_uint<1>("0bus1")) & ((sc_uint<5>)(a_man(15,11)))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:4767
    // Compare anchor: inst_mult_d_cellmath__64__67
    inst_mult_d_cellmath__64__67 = 
        (inst_mult_d_cellmath__64__68(0,0),inst_mult_d_cellmath__64__70,sc_uint<1>(0),a_man(10,10))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:3332
    // Compare anchor: inst_mult_d_cellmath__64__64(0,0)
    inst_mult_d_cellmath__64__64(0,0) = 
        
            ((sc_uint<1>)((sc_uint<1>)(a_man(9,9))))
            &((sc_uint<1>)((sc_uint<1>)(inst_cellmath__35)))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:4536
    // Compare anchor: inst_mult_d_cellmath__64__63(0,0)
    inst_mult_d_cellmath__64__63(0,0) = 
        ~(sc_uint<1>)(inst_mult_d_cellmath__64__64(0,0))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:2018
    // !!!! amethyst/writers/SystemCbeh.cpp:2041
    // Compare anchor: inst_mult_d_cellmath__64__65
    inst_mult_d_cellmath__64__65 = 
        
        -(int)((sc_uint<1>)a_man(9,9) == sc_uint<1>("0bus1")) & ((sc_uint<6>)(a_man(15,10)))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:4767
    // Compare anchor: inst_mult_d_cellmath__64__62
    inst_mult_d_cellmath__64__62 = 
        (inst_mult_d_cellmath__64__63(0,0),inst_mult_d_cellmath__64__65,sc_uint<1>(0),a_man(9,9))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:3332
    // Compare anchor: inst_mult_d_cellmath__64__59(0,0)
    inst_mult_d_cellmath__64__59(0,0) = 
        
            ((sc_uint<1>)((sc_uint<1>)(a_man(8,8))))
            &((sc_uint<1>)((sc_uint<1>)(inst_cellmath__35)))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:4536
    // Compare anchor: inst_mult_d_cellmath__64__58(0,0)
    inst_mult_d_cellmath__64__58(0,0) = 
        ~(sc_uint<1>)(inst_mult_d_cellmath__64__59(0,0))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:2018
    // !!!! amethyst/writers/SystemCbeh.cpp:2041
    // Compare anchor: inst_mult_d_cellmath__64__60
    inst_mult_d_cellmath__64__60 = 
        
        -(int)((sc_uint<1>)a_man(8,8) == sc_uint<1>("0bus1")) & ((sc_uint<7>)(a_man(15,9)))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:4767
    // Compare anchor: inst_mult_d_cellmath__64__57
    inst_mult_d_cellmath__64__57 = 
        (inst_mult_d_cellmath__64__58(0,0),inst_mult_d_cellmath__64__60,sc_uint<1>(0),a_man(8,8))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:3332
    // Compare anchor: inst_mult_d_cellmath__64__54(0,0)
    inst_mult_d_cellmath__64__54(0,0) = 
        
            ((sc_uint<1>)((sc_uint<1>)(a_man(7,7))))
            &((sc_uint<1>)((sc_uint<1>)(inst_cellmath__35)))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:4536
    // Compare anchor: inst_mult_d_cellmath__64__53(0,0)
    inst_mult_d_cellmath__64__53(0,0) = 
        ~(sc_uint<1>)(inst_mult_d_cellmath__64__54(0,0))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:2018
    // !!!! amethyst/writers/SystemCbeh.cpp:2041
    // Compare anchor: inst_mult_d_cellmath__64__55
    inst_mult_d_cellmath__64__55 = 
        
        -(int)((sc_uint<1>)a_man(7,7) == sc_uint<1>("0bus1")) & ((sc_uint<8>)(a_man(15,8)))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:4767
    // Compare anchor: inst_mult_d_cellmath__64__52
    inst_mult_d_cellmath__64__52 = 
        (inst_mult_d_cellmath__64__53(0,0),inst_mult_d_cellmath__64__55,sc_uint<1>(0),a_man(7,7))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:3332
    // Compare anchor: inst_mult_d_cellmath__64__49(0,0)
    inst_mult_d_cellmath__64__49(0,0) = 
        
            ((sc_uint<1>)((sc_uint<1>)(a_man(6,6))))
            &((sc_uint<1>)((sc_uint<1>)(inst_cellmath__35)))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:4536
    // Compare anchor: inst_mult_d_cellmath__64__48(0,0)
    inst_mult_d_cellmath__64__48(0,0) = 
        ~(sc_uint<1>)(inst_mult_d_cellmath__64__49(0,0))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:2018
    // !!!! amethyst/writers/SystemCbeh.cpp:2041
    // Compare anchor: inst_mult_d_cellmath__64__50
    inst_mult_d_cellmath__64__50 = 
        
        -(int)((sc_uint<1>)a_man(6,6) == sc_uint<1>("0bus1")) & ((sc_uint<9>)(a_man(15,7)))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:4767
    // Compare anchor: inst_mult_d_cellmath__64__47
    inst_mult_d_cellmath__64__47 = 
        (inst_mult_d_cellmath__64__48(0,0),inst_mult_d_cellmath__64__50,sc_uint<1>(0),a_man(6,6))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:3332
    // Compare anchor: inst_mult_d_cellmath__64__44(0,0)
    inst_mult_d_cellmath__64__44(0,0) = 
        
            ((sc_uint<1>)((sc_uint<1>)(a_man(5,5))))
            &((sc_uint<1>)((sc_uint<1>)(inst_cellmath__35)))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:4536
    // Compare anchor: inst_mult_d_cellmath__64__43(0,0)
    inst_mult_d_cellmath__64__43(0,0) = 
        ~(sc_uint<1>)(inst_mult_d_cellmath__64__44(0,0))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:2018
    // !!!! amethyst/writers/SystemCbeh.cpp:2041
    // Compare anchor: inst_mult_d_cellmath__64__45
    inst_mult_d_cellmath__64__45 = 
        
        -(int)((sc_uint<1>)a_man(5,5) == sc_uint<1>("0bus1")) & ((sc_uint<10>)(a_man(15,6)))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:4767
    // Compare anchor: inst_mult_d_cellmath__64__42
    inst_mult_d_cellmath__64__42 = 
        (inst_mult_d_cellmath__64__43(0,0),inst_mult_d_cellmath__64__45,sc_uint<1>(0),a_man(5,5))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:3332
    // Compare anchor: inst_mult_d_cellmath__64__39(0,0)
    inst_mult_d_cellmath__64__39(0,0) = 
        
            ((sc_uint<1>)((sc_uint<1>)(a_man(4,4))))
            &((sc_uint<1>)((sc_uint<1>)(inst_cellmath__35)))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:4536
    // Compare anchor: inst_mult_d_cellmath__64__38(0,0)
    inst_mult_d_cellmath__64__38(0,0) = 
        ~(sc_uint<1>)(inst_mult_d_cellmath__64__39(0,0))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:2018
    // !!!! amethyst/writers/SystemCbeh.cpp:2041
    // Compare anchor: inst_mult_d_cellmath__64__40
    inst_mult_d_cellmath__64__40 = 
        
        -(int)((sc_uint<1>)a_man(4,4) == sc_uint<1>("0bus1")) & ((sc_uint<11>)(a_man(15,5)))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:4767
    // Compare anchor: inst_mult_d_cellmath__64__37
    inst_mult_d_cellmath__64__37 = 
        (inst_mult_d_cellmath__64__38(0,0),inst_mult_d_cellmath__64__40,sc_uint<1>(0),a_man(4,4))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:3332
    // Compare anchor: inst_mult_d_cellmath__64__29(0,0)
    inst_mult_d_cellmath__64__29(0,0) = 
        
            ((sc_uint<1>)((sc_uint<1>)(a_man(2,2))))
            &((sc_uint<1>)((sc_uint<1>)(inst_cellmath__35)))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:4536
    // Compare anchor: inst_mult_d_cellmath__64__28(0,0)
    inst_mult_d_cellmath__64__28(0,0) = 
        ~(sc_uint<1>)(inst_mult_d_cellmath__64__29(0,0))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:2018
    // !!!! amethyst/writers/SystemCbeh.cpp:2041
    // Compare anchor: inst_mult_d_cellmath__64__30
    inst_mult_d_cellmath__64__30 = 
        
        -(int)((sc_uint<1>)a_man(2,2) == sc_uint<1>("0bus1")) & ((sc_uint<13>)(a_man(15,3)))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:4767
    // Compare anchor: inst_mult_d_cellmath__64__27
    inst_mult_d_cellmath__64__27 = 
        (inst_mult_d_cellmath__64__28(0,0),inst_mult_d_cellmath__64__30,sc_uint<1>(0),a_man(2,2))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:3332
    // Compare anchor: inst_mult_d_cellmath__64__34(0,0)
    inst_mult_d_cellmath__64__34(0,0) = 
        
            ((sc_uint<1>)((sc_uint<1>)(a_man(3,3))))
            &((sc_uint<1>)((sc_uint<1>)(inst_cellmath__35)))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:4536
    // Compare anchor: inst_mult_d_cellmath__64__33(0,0)
    inst_mult_d_cellmath__64__33(0,0) = 
        ~(sc_uint<1>)(inst_mult_d_cellmath__64__34(0,0))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:2018
    // !!!! amethyst/writers/SystemCbeh.cpp:2041
    // Compare anchor: inst_mult_d_cellmath__64__35
    inst_mult_d_cellmath__64__35 = 
        
        -(int)((sc_uint<1>)a_man(3,3) == sc_uint<1>("0bus1")) & ((sc_uint<12>)(a_man(15,4)))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:4767
    // Compare anchor: inst_mult_d_cellmath__64__32
    inst_mult_d_cellmath__64__32 = 
        (inst_mult_d_cellmath__64__33(0,0),inst_mult_d_cellmath__64__35,sc_uint<1>(0),a_man(3,3))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:2912
    sc_uint<29> inst_mult_d_cellmath__64_tmp_9;
    // !!!! amethyst/writers/SystemCbeh.cpp:2912
    sc_uint<29> inst_mult_d_cellmath__64_tmp_10;
    // !!!! amethyst/writers/SystemCbeh.cpp:2912
    sc_uint<29> inst_mult_d_cellmath__64_tmp_11;
    // !!!! amethyst/writers/SystemCbeh.cpp:2912
    sc_uint<29> inst_mult_d_cellmath__64_tmp_12;
    // !!!! amethyst/writers/SystemCbeh.cpp:2912
    sc_uint<29> inst_mult_d_cellmath__64_tmp_13;
    // !!!! amethyst/writers/SystemCbeh.cpp:2912
    sc_uint<29> inst_mult_d_cellmath__64_tmp_14;
    // !!!! amethyst/writers/SystemCbeh.cpp:2912
    sc_uint<29> inst_mult_d_cellmath__64_tmp_15;
    // !!!! amethyst/writers/SystemCbeh.cpp:2912
    sc_uint<29> inst_mult_d_cellmath__64_tmp_16;
    // !!!! amethyst/writers/SystemCbeh.cpp:2912
    sc_uint<29> inst_mult_d_cellmath__64_tmp_17;
    // !!!! amethyst/writers/SystemCbeh.cpp:2912
    sc_uint<29> inst_mult_d_cellmath__64_tmp_18;
    // !!!! amethyst/writers/SystemCbeh.cpp:2912
    sc_uint<29> inst_mult_d_cellmath__64_tmp_19;
    // !!!! amethyst/writers/SystemCbeh.cpp:2912
    sc_uint<29> inst_mult_d_cellmath__64_tmp_20;
    // !!!! amethyst/writers/SystemCbeh.cpp:2912
    sc_uint<29> inst_mult_d_cellmath__64_tmp_21;
    // !!!! amethyst/writers/SystemCbeh.cpp:2912
    sc_uint<29> inst_mult_d_cellmath__64_tmp_22;
    // !!!! amethyst/writers/SystemCbeh.cpp:2912
    // !!!! amethyst/writers/SystemCbeh.cpp:3086
    // Compare anchor: inst_mult_d_cellmath__64_tmp_22
    inst_mult_d_cellmath__64_tmp_22 = 
        
            +((sc_uint<29>)(((sc_uint<29>)((inst_cellmath__35)<<(shift_v)28))))
            +((sc_uint<29>)(((sc_uint<29>)((inst_mult_d_cellmath__64__92)<<(shift_v)26))))
    ;
    // !!!! amethyst/writers/SystemCbeh.cpp:3086
    // Compare anchor: inst_mult_d_cellmath__64_tmp_21
    inst_mult_d_cellmath__64_tmp_21 = 
        inst_mult_d_cellmath__64_tmp_22
            +((sc_uint<29>)(((sc_uint<29>)((inst_mult_d_cellmath__64__87)<<(shift_v)24))))
    ;
    // !!!! amethyst/writers/SystemCbeh.cpp:3086
    // Compare anchor: inst_mult_d_cellmath__64_tmp_20
    inst_mult_d_cellmath__64_tmp_20 = 
        inst_mult_d_cellmath__64_tmp_21
            +((sc_uint<29>)(((sc_uint<29>)((inst_mult_d_cellmath__64__82)<<(shift_v)22))))
    ;
    // !!!! amethyst/writers/SystemCbeh.cpp:3086
    // Compare anchor: inst_mult_d_cellmath__64_tmp_19
    inst_mult_d_cellmath__64_tmp_19 = 
        inst_mult_d_cellmath__64_tmp_20
            +((sc_uint<29>)(((sc_uint<29>)((inst_mult_d_cellmath__64__77)<<(shift_v)20))))
    ;
    // !!!! amethyst/writers/SystemCbeh.cpp:3086
    // Compare anchor: inst_mult_d_cellmath__64_tmp_18
    inst_mult_d_cellmath__64_tmp_18 = 
        inst_mult_d_cellmath__64_tmp_19
            +((sc_uint<29>)(((sc_uint<29>)((inst_mult_d_cellmath__64__72)<<(shift_v)18))))
    ;
    // !!!! amethyst/writers/SystemCbeh.cpp:3086
    // Compare anchor: inst_mult_d_cellmath__64_tmp_17
    inst_mult_d_cellmath__64_tmp_17 = 
        inst_mult_d_cellmath__64_tmp_18
            +((sc_uint<29>)(((sc_uint<29>)((inst_mult_d_cellmath__64__67)<<(shift_v)16))))
    ;
    // !!!! amethyst/writers/SystemCbeh.cpp:3086
    // Compare anchor: inst_mult_d_cellmath__64_tmp_16
    inst_mult_d_cellmath__64_tmp_16 = 
        inst_mult_d_cellmath__64_tmp_17
            +((sc_uint<29>)(((sc_uint<29>)((inst_mult_d_cellmath__64__62)<<(shift_v)14))))
    ;
    // !!!! amethyst/writers/SystemCbeh.cpp:3086
    // Compare anchor: inst_mult_d_cellmath__64_tmp_15
    inst_mult_d_cellmath__64_tmp_15 = 
        inst_mult_d_cellmath__64_tmp_16
            +((sc_uint<29>)(((sc_uint<29>)((inst_mult_d_cellmath__64__57)<<(shift_v)12))))
    ;
    // !!!! amethyst/writers/SystemCbeh.cpp:3086
    // Compare anchor: inst_mult_d_cellmath__64_tmp_14
    inst_mult_d_cellmath__64_tmp_14 = 
        inst_mult_d_cellmath__64_tmp_15
            +((sc_uint<29>)(((sc_uint<29>)((inst_mult_d_cellmath__64__52)<<(shift_v)10))))
    ;
    // !!!! amethyst/writers/SystemCbeh.cpp:3086
    // Compare anchor: inst_mult_d_cellmath__64_tmp_13
    inst_mult_d_cellmath__64_tmp_13 = 
        inst_mult_d_cellmath__64_tmp_14
            +((sc_uint<29>)(((sc_uint<29>)((inst_mult_d_cellmath__64__47)<<(shift_v)8))))
    ;
    // !!!! amethyst/writers/SystemCbeh.cpp:3086
    // Compare anchor: inst_mult_d_cellmath__64_tmp_12
    inst_mult_d_cellmath__64_tmp_12 = 
        inst_mult_d_cellmath__64_tmp_13
            +((sc_uint<29>)(((sc_uint<29>)((inst_mult_d_cellmath__64__42)<<(shift_v)6))))
    ;
    // !!!! amethyst/writers/SystemCbeh.cpp:3086
    // Compare anchor: inst_mult_d_cellmath__64_tmp_11
    inst_mult_d_cellmath__64_tmp_11 = 
        inst_mult_d_cellmath__64_tmp_12
            +((sc_uint<29>)(((sc_uint<29>)((inst_mult_d_cellmath__64__37)<<(shift_v)4))))
    ;
    // !!!! amethyst/writers/SystemCbeh.cpp:3086
    // Compare anchor: inst_mult_d_cellmath__64_tmp_10
    inst_mult_d_cellmath__64_tmp_10 = 
        inst_mult_d_cellmath__64_tmp_11
            +((sc_uint<29>)(inst_mult_d_cellmath__64__27))
    ;
    // !!!! amethyst/writers/SystemCbeh.cpp:3086
    // Compare anchor: inst_mult_d_cellmath__64_tmp_9
    inst_mult_d_cellmath__64_tmp_9 = 
        inst_mult_d_cellmath__64_tmp_10
            +((sc_uint<29>)(((sc_uint<29>)((inst_mult_d_cellmath__64__32)<<(shift_v)2))))
    ;
    // !!!! amethyst/writers/SystemCbeh.cpp:3086
    // Compare anchor: inst_mult_d_cellmath__64(28,0)
    inst_mult_d_cellmath__64(28,0) = 
        inst_mult_d_cellmath__64_tmp_9
            +((sc_uint<29>)(sc_uint<17>("0bus01000000000000000")))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:2018
    // !!!! amethyst/writers/SystemCbeh.cpp:2041
    // Compare anchor: inst_cellmath__59_0
	inst_cellmath__59_0 = 0;

        
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0000000")) & ((sc_uint<56>)(sc_uint<56>("0bus01101000101000011111100000100110100010011101100001010010")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0000001")) & ((sc_uint<56>)(sc_uint<56>("0bus01100101110111101000001010101000100101000101100000000010")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0000010")) & ((sc_uint<56>)(sc_uint<56>("0bus01100011001010110001001000101010100010110100011110110110")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0000011")) & ((sc_uint<56>)(sc_uint<56>("0bus01100000100001110000110110101100011011111010011101101110")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0000100")) & ((sc_uint<56>)(sc_uint<56>("0bus01011101111100011110010010101110010000100110011100101001")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0000101")) & ((sc_uint<56>)(sc_uint<56>("0bus01011011011010110000111000110000000001000110011011101000")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0000110")) & ((sc_uint<56>)(sc_uint<56>("0bus01011000111100100000011110110001101101101000011010101010")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0000111")) & ((sc_uint<56>)(sc_uint<56>("0bus01010110100001100101010010110011010110011000011001101111")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0001000")) & ((sc_uint<56>)(sc_uint<56>("0bus01010100001001110111111110110100111011100001011000110110")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0001001")) & ((sc_uint<56>)(sc_uint<56>("0bus01010001110101010001011110110110011101001111011000000001")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0001010")) & ((sc_uint<56>)(sc_uint<56>("0bus01001111100011101011000110110111111011101100010111001110")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0001011")) & ((sc_uint<56>)(sc_uint<56>("0bus01001101010100111110011110111001010111000010010110011101")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0001100")) & ((sc_uint<56>)(sc_uint<56>("0bus01001011001001000101100010111010101111011001010101101111")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0001101")) & ((sc_uint<56>)(sc_uint<56>("0bus01001000111111111010011010111100000100111010010101000010")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0001110")) & ((sc_uint<56>)(sc_uint<56>("0bus01000110111001010111100110111101010111101101010100011000")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0001111")) & ((sc_uint<56>)(sc_uint<56>("0bus01000100110101010111110010111110100111111010010011101111")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0010000")) & ((sc_uint<56>)(sc_uint<56>("0bus01000010110011110101110110111111110101101001010011001000")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0010001")) & ((sc_uint<56>)(sc_uint<56>("0bus01000000110100101100111111000001000000111111010010100011")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0010010")) & ((sc_uint<56>)(sc_uint<56>("0bus00111110110111111000100001000010001010000100010001111111")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0010011")) & ((sc_uint<56>)(sc_uint<56>("0bus00111100111101010011111101000011010000111100010001011101")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0010100")) & ((sc_uint<56>)(sc_uint<56>("0bus00111011000100111011000101000100010101110000010000111100")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0010101")) & ((sc_uint<56>)(sc_uint<56>("0bus00111001001110101001110011000101011000100010010000011101")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0010110")) & ((sc_uint<56>)(sc_uint<56>("0bus00110111011010011100001001000110011001011010001111111111")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0010111")) & ((sc_uint<56>)(sc_uint<56>("0bus00110101101000001110010101000111011000011011001111100010")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0011000")) & ((sc_uint<56>)(sc_uint<56>("0bus00110011110111111100110011001000010101101011001111000110")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0011001")) & ((sc_uint<56>)(sc_uint<56>("0bus00110010001001100100000001001001010001001101001110101011")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0011010")) & ((sc_uint<56>)(sc_uint<56>("0bus00110000011101000000101011001010001011000111001110010010")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0011011")) & ((sc_uint<56>)(sc_uint<56>("0bus00101110110010001111100001001011000011011011001101111001")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0011100")) & ((sc_uint<56>)(sc_uint<56>("0bus00101101001001001101011101001011111010001110001101100001")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0011101")) & ((sc_uint<56>)(sc_uint<56>("0bus00101011100001110111100011001100101111100100001101001010")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0011110")) & ((sc_uint<56>)(sc_uint<56>("0bus00101001111100001010111011001101100011100000001100110100")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0011111")) & ((sc_uint<56>)(sc_uint<56>("0bus00101000011000000100110001001110010110000101001100011111")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0100000")) & ((sc_uint<56>)(sc_uint<56>("0bus00100110110101100010011101001111000111010110001100001010")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0100001")) & ((sc_uint<56>)(sc_uint<56>("0bus00100101010100100001011011001111110111010111001011110110")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0100010")) & ((sc_uint<56>)(sc_uint<56>("0bus00100011110100111111001011010000100110001010001011100011")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0100011")) & ((sc_uint<56>)(sc_uint<56>("0bus00100010010110111001010101010001010011110010001011010001")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0100100")) & ((sc_uint<56>)(sc_uint<56>("0bus00100000111010001101100101010010000000010001001010111111")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0100101")) & ((sc_uint<56>)(sc_uint<56>("0bus00011111011110111001101111010010101011101010001010101110")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0100110")) & ((sc_uint<56>)(sc_uint<56>("0bus00011110000100111011100111010011010110000000001010011101")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0100111")) & ((sc_uint<56>)(sc_uint<56>("0bus00011100101100010001001001010011111111010101001010001101")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0101000")) & ((sc_uint<56>)(sc_uint<56>("0bus00011011010100111000010101010100100111101010001001111110")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0101001")) & ((sc_uint<56>)(sc_uint<56>("0bus00011001111110101111001101010101001111000011001001101111")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0101010")) & ((sc_uint<56>)(sc_uint<56>("0bus00011000101001110011111011010101110101100000001001100000")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0101011")) & ((sc_uint<56>)(sc_uint<56>("0bus00010111010110000100101001010110011011000100001001010010")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0101100")) & ((sc_uint<56>)(sc_uint<56>("0bus00010110000011011111101001010110111111110001001001000100")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0101101")) & ((sc_uint<56>)(sc_uint<56>("0bus00010100110010000011001101010111100011101001001000110111")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0101110")) & ((sc_uint<56>)(sc_uint<56>("0bus00010011100001101101101101011000000110101100001000101011")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0101111")) & ((sc_uint<56>)(sc_uint<56>("0bus00010010010010011101011111011000101000111110001000011110")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0110000")) & ((sc_uint<56>)(sc_uint<56>("0bus00010001000100010001000101011001001010011111001000010010")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0110001")) & ((sc_uint<56>)(sc_uint<56>("0bus00001111110111000110111101011001101011010000001000000111")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0110010")) & ((sc_uint<56>)(sc_uint<56>("0bus00001110101010111101101001011010001011010100000111111011")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0110011")) & ((sc_uint<56>)(sc_uint<56>("0bus00001101011111110011110011011010101010101100000111110000")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0110100")) & ((sc_uint<56>)(sc_uint<56>("0bus00001100010101100111111111011011001001011001000111100110")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0110101")) & ((sc_uint<56>)(sc_uint<56>("0bus00001011001100011000111011011011100111011100000111011100")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0110110")) & ((sc_uint<56>)(sc_uint<56>("0bus00001010000100000101010011011100000100110110000111010010")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0110111")) & ((sc_uint<56>)(sc_uint<56>("0bus00001000111100101011111001011100100001101001000111001000")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0111000")) & ((sc_uint<56>)(sc_uint<56>("0bus00000111110110001011100001011100111101110110000110111111")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0111001")) & ((sc_uint<56>)(sc_uint<56>("0bus00000110110000100010111011011101011001011110000110110101")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0111010")) & ((sc_uint<56>)(sc_uint<56>("0bus00000101101011110001000001011101110100100010000110101101")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0111011")) & ((sc_uint<56>)(sc_uint<56>("0bus00000100100111110100101101011110001111000011000110100100")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0111100")) & ((sc_uint<56>)(sc_uint<56>("0bus00000011100100101100111001011110101001000010000110011100")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0111101")) & ((sc_uint<56>)(sc_uint<56>("0bus00000010100010011000011111011111000010100000000110010011")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0111110")) & ((sc_uint<56>)(sc_uint<56>("0bus00000001100000110110100011011111011011011110000110001011")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus0111111")) & ((sc_uint<56>)(sc_uint<56>("0bus00000000100000000110000011011111110011111100000110000100")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1000000")) & ((sc_uint<56>)(sc_uint<56>("0bus11111110000000101111101100000001011110110111101111000101")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1000001")) & ((sc_uint<56>)(sc_uint<56>("0bus11111010000110100111101110000100010111100110101101010011")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1000010")) & ((sc_uint<56>)(sc_uint<56>("0bus11110110010010001010001110000111001001011001101011100111")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1000011")) & ((sc_uint<56>)(sc_uint<56>("0bus11110010100011001001101100001001110100101001101010000001")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1000100")) & ((sc_uint<56>)(sc_uint<56>("0bus11101110111001011001011000001100011001101011101000100000")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1000101")) & ((sc_uint<56>)(sc_uint<56>("0bus11101011010100101101000110001110111000110001100111000100")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1000110")) & ((sc_uint<56>)(sc_uint<56>("0bus11100111110100111001010110010001010010010000100101101100")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1000111")) & ((sc_uint<56>)(sc_uint<56>("0bus11100100011001110011001010010011100110011001100100011001")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1001000")) & ((sc_uint<56>)(sc_uint<56>("0bus11100001000011010000000110010101110101011100100011001001")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1001001")) & ((sc_uint<56>)(sc_uint<56>("0bus11011101110001000110001110010111111111101000100001111101")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1001010")) & ((sc_uint<56>)(sc_uint<56>("0bus11011010100011001100000100011010000101001101100000110101")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1001011")) & ((sc_uint<56>)(sc_uint<56>("0bus11010111011001011000100110011100000110011000011111110000")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1001100")) & ((sc_uint<56>)(sc_uint<56>("0bus11010100010011100011001110011110000011010101011110101111")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1001101")) & ((sc_uint<56>)(sc_uint<56>("0bus11010001010001100011101100011111111100010001011101110000")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1001110")) & ((sc_uint<56>)(sc_uint<56>("0bus11001110010011010010001010100001110001011000011100110100")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1001111")) & ((sc_uint<56>)(sc_uint<56>("0bus11001011011000100111001000100011100010110011011011111010")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1010000")) & ((sc_uint<56>)(sc_uint<56>("0bus11001000100001011011011000100101010000101110011011000011")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1010001")) & ((sc_uint<56>)(sc_uint<56>("0bus11000101101101101000000110100110111011010010011010001111")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1010010")) & ((sc_uint<56>)(sc_uint<56>("0bus11000010111101000110101100101000100010100111011001011100")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1010011")) & ((sc_uint<56>)(sc_uint<56>("0bus11000000001111110000110110101010000110110111011000101100")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1010100")) & ((sc_uint<56>)(sc_uint<56>("0bus10111101100101100000100000101011101000001010010111111110")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1010101")) & ((sc_uint<56>)(sc_uint<56>("0bus10111010111110001111111000101101000110101000010111010001")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1010110")) & ((sc_uint<56>)(sc_uint<56>("0bus10111000011001111001011100101110100010010111010110100111")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1010111")) & ((sc_uint<56>)(sc_uint<56>("0bus10110101111000010111110110101111111011011111010101111110")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1011000")) & ((sc_uint<56>)(sc_uint<56>("0bus10110011011001100101111100110001010010000110010101010110")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1011001")) & ((sc_uint<56>)(sc_uint<56>("0bus10110000111101011110110110110010100110010011010100110000")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1011010")) & ((sc_uint<56>)(sc_uint<56>("0bus10101110100011111101110010110011111000001011010100001100")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1011011")) & ((sc_uint<56>)(sc_uint<56>("0bus10101100001100111110010000110101000111110101010011101001")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1011100")) & ((sc_uint<56>)(sc_uint<56>("0bus10101001111000011011110110110110010101010101010011000111")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1011101")) & ((sc_uint<56>)(sc_uint<56>("0bus10100111100110010010011000110111100000110001010010100111")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1011110")) & ((sc_uint<56>)(sc_uint<56>("0bus10100101010110011101110000111000101010001101010010001000")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1011111")) & ((sc_uint<56>)(sc_uint<56>("0bus10100011001000111010000110111001110001101111010001101001")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1100000")) & ((sc_uint<56>)(sc_uint<56>("0bus10100000111101100011101000111010110111011010010001001100")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1100001")) & ((sc_uint<56>)(sc_uint<56>("0bus10011110110100010110101110111011111011010100010000110000")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1100010")) & ((sc_uint<56>)(sc_uint<56>("0bus10011100101101001111111000111100111101011111010000010101")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1100011")) & ((sc_uint<56>)(sc_uint<56>("0bus10011010101000001011101100111101111110000000001111111011")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1100100")) & ((sc_uint<56>)(sc_uint<56>("0bus10011000100101000110111110111110111100111011001111100010")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1100101")) & ((sc_uint<56>)(sc_uint<56>("0bus10010110100011111110100000111111111010010011001111001010")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1100110")) & ((sc_uint<56>)(sc_uint<56>("0bus10010100100100101111010011000000110110001011001110110010")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1100111")) & ((sc_uint<56>)(sc_uint<56>("0bus10010010100111010110011001000001110000100111001110011100")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1101000")) & ((sc_uint<56>)(sc_uint<56>("0bus10010000101011110000111011000010101001101010001110000110")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1101001")) & ((sc_uint<56>)(sc_uint<56>("0bus10001110110001111100001101000011100001010110001101110001")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1101010")) & ((sc_uint<56>)(sc_uint<56>("0bus10001100111001110101100011000100010111101111001101011100")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1101011")) & ((sc_uint<56>)(sc_uint<56>("0bus10001011000011011010011011000101001100110111001101001000")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1101100")) & ((sc_uint<56>)(sc_uint<56>("0bus10001001001110101000010011000110000000110001001100110101")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1101101")) & ((sc_uint<56>)(sc_uint<56>("0bus10000111011011011100110011000110110011100000001100100010")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1101110")) & ((sc_uint<56>)(sc_uint<56>("0bus10000101101001110101100101000111100101000101001100010000")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1101111")) & ((sc_uint<56>)(sc_uint<56>("0bus10000011111001110000011011001000010101100011001011111111")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1110000")) & ((sc_uint<56>)(sc_uint<56>("0bus10000010001011001011000111001001000100111100001011101110")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1110001")) & ((sc_uint<56>)(sc_uint<56>("0bus10000000011110000011100011001001110011010011001011011101")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1110010")) & ((sc_uint<56>)(sc_uint<56>("0bus01111110110010010111101001001010100000101000001011001110")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1110011")) & ((sc_uint<56>)(sc_uint<56>("0bus01111101001000000101011111001011001101000000001010111110")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1110100")) & ((sc_uint<56>)(sc_uint<56>("0bus01111011011111001011000011001011111000011010001010101111")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1110101")) & ((sc_uint<56>)(sc_uint<56>("0bus01111001110111100110100011001100100010111010001010100001")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1110110")) & ((sc_uint<56>)(sc_uint<56>("0bus01111000010001010110000111001101001100100000001010010011")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1110111")) & ((sc_uint<56>)(sc_uint<56>("0bus01110110101100011000000001001101110101001111001010000101")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1111000")) & ((sc_uint<56>)(sc_uint<56>("0bus01110101001000101010100001001110011101000111001001111000")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1111001")) & ((sc_uint<56>)(sc_uint<56>("0bus01110011100110001011111101001111000100001100001001101011")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1111010")) & ((sc_uint<56>)(sc_uint<56>("0bus01110010000100111010101111001111101010011101001001011110")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1111011")) & ((sc_uint<56>)(sc_uint<56>("0bus01110000100100110101010011010000001111111101001001010010")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1111100")) & ((sc_uint<56>)(sc_uint<56>("0bus01101111000101111010000101010000110100101101001001000110")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1111101")) & ((sc_uint<56>)(sc_uint<56>("0bus01101101101000000111100111010001011000101110001000111011")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1111110")) & ((sc_uint<56>)(sc_uint<56>("0bus01101100001011011100011101010001111100000001001000101111")));
        inst_cellmath__59_0 |= -(int)((sc_uint<7>)tmp_0_23_17_ == sc_uint<7>("0bus1111111")) & ((sc_uint<56>)(sc_uint<56>("0bus01101010101111110111001111010010011110101000001000100100")));
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:2912
    // !!!! amethyst/writers/SystemCbeh.cpp:3086
    // Compare anchor: inst_FP_RSQ_MULT_C_mult_c_datapath_prodSum(25,0)
    inst_FP_RSQ_MULT_C_mult_c_datapath_prodSum(25,0) = 
        
            +(/*conformal multiplier wall*/(sc_uint<26>)(inst_cellmath__59_0(11,0)) * (sc_uint<26>)(inst_mult_d_cellmath__64(28,15)))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:4767
    // Compare anchor: inst_cellmath__60
    inst_cellmath__60 = 
        (sc_uint<1>(1),inst_cellmath__59_0(30,12))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:4767
    // Compare anchor: inst_cellmath__37
    inst_cellmath__37 = 
        (inst_cellmath__35,a_man(15,0))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:2912
    // !!!! amethyst/writers/SystemCbeh.cpp:3086
    // Compare anchor: inst_FP_RSQ_MULT_B_mult_b_datapath_prodSum(35,0)
    inst_FP_RSQ_MULT_B_mult_b_datapath_prodSum(35,0) = 
        
            +(/*conformal multiplier wall*/(sc_uint<36>)(( ((sc_uint<19>)(sc_int<1>)(inst_cellmath__37(16,16))), inst_cellmath__37)) * (sc_uint<36>)(( ((sc_uint<16>)(sc_int<1>)(inst_cellmath__60(19,19))), inst_cellmath__60)))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:2912
    sc_uint<42> inst_cellmath__72_tmp_23;
    // !!!! amethyst/writers/SystemCbeh.cpp:2912
    sc_uint<42> inst_cellmath__72_tmp_24;
    // !!!! amethyst/writers/SystemCbeh.cpp:2912
    // !!!! amethyst/writers/SystemCbeh.cpp:3086
    // Compare anchor: inst_cellmath__72_tmp_24
    inst_cellmath__72_tmp_24 = 
        
            +((sc_uint<42>)(((sc_uint<42>)(((sc_uint<42>)(( ((sc_uint<13>)(sc_int<1>)(inst_FP_RSQ_MULT_C_mult_c_datapath_prodSum(25,25))), inst_FP_RSQ_MULT_C_mult_c_datapath_prodSum(25,0))))<<(shift_v)3))))
            +((sc_uint<42>)(((sc_uint<42>)((inst_cellmath__59_0(55,31))<<(shift_v)17))))
    ;
    // !!!! amethyst/writers/SystemCbeh.cpp:3086
    // Compare anchor: inst_cellmath__72_tmp_23
    inst_cellmath__72_tmp_23 = 
        inst_cellmath__72_tmp_24
            +((sc_uint<42>)(( ((sc_uint<6>)(sc_int<1>)(inst_FP_RSQ_MULT_B_mult_b_datapath_prodSum(35,35))), (sc_biguint<36>)(inst_FP_RSQ_MULT_B_mult_b_datapath_prodSum(35,0)))))
    ;
    // !!!! amethyst/writers/SystemCbeh.cpp:3086
    // Compare anchor: inst_cellmath__72
    inst_cellmath__72 = 
        inst_cellmath__72_tmp_23
            +((sc_uint<42>)(sc_uint<20>("0bus01000000000000000000")))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:2018
    // !!!! amethyst/writers/SystemCbeh.cpp:2041
    // Compare anchor: inst_cellmath__74
    inst_cellmath__74 = 
        
        -(int)((sc_uint<3>)inst_cellmath__29_0 == sc_uint<3>("0bus000")) & ((sc_uint<23>)(inst_cellmath__72(41,19))) |
        -(int)((sc_uint<1>)inst_cellmath__29_0(2,2) == sc_uint<1>("0bus1")) & ((sc_uint<23>)(sc_uint<23>("0bus11111111111111111111111")))
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:4767
    // Compare anchor: inst_cellmath__80
    inst_cellmath__80 = 
        (inst_cellmath__33,inst_cellmath__74)
    ;

    // !!!! amethyst/writers/SystemCbeh.cpp:4536
    // Compare anchor: x
    x = 
        (sc_uint<32>)(inst_cellmath__80)
    ;

/*Clock change logic follows*/
}

// Signal declarations:

    sc_uint<1> inst_cellmath__16;
    sc_uint<1> inst_cellmath__17;
    sc_uint<1> inst_cellmath__18;
    sc_uint<1> inst_cellmath__20;
    sc_uint<1> inst_cellmath__22;
    sc_uint<1> inst_cellmath__24;
    sc_uint<1> inst_cellmath__25;
    sc_uint<1> inst_cellmath__26;
    sc_uint<1> inst_cellmath__29;
    sc_uint<1> inst_cellmath__30;
    sc_uint<1> inst_cellmath__31;
    sc_uint<8> inst_cellmath__33;
    sc_uint<1> inst_cellmath__35;
    sc_int<17> inst_cellmath__37;
    sc_int<20> inst_cellmath__60;
    sc_int<31> inst_mult_d_cellmath__64;
    sc_int<28> inst_FP_RSQ_MULT_C_mult_c_datapath_prodSum;
    sc_int<39> inst_FP_RSQ_MULT_B_mult_b_datapath_prodSum;
    sc_uint<42> inst_cellmath__72;
    sc_uint<23> inst_cellmath__74;
    sc_uint<32> inst_cellmath__80;
    sc_uint<1> inst_cellmath__22__7;
    sc_int<9> inst_cellmath__22__6;
    sc_uint<1> inst_cellmath__22__8;
    sc_uint<1> inst_cellmath__22__4;
    sc_uint<1> inst_cellmath__26__9;
    sc_uint<1> inst_cellmath__30__14;
    sc_uint<1> inst_cellmath__31__15;
    sc_uint<1> inst_cellmath__33__23;
    sc_int<2> inst_mult_d_cellmath__64__29;
    sc_int<2> inst_mult_d_cellmath__64__28;
    sc_uint<13> inst_mult_d_cellmath__64__30;
    sc_uint<16> inst_mult_d_cellmath__64__27;
    sc_int<2> inst_mult_d_cellmath__64__34;
    sc_int<2> inst_mult_d_cellmath__64__33;
    sc_uint<12> inst_mult_d_cellmath__64__35;
    sc_uint<15> inst_mult_d_cellmath__64__32;
    sc_int<2> inst_mult_d_cellmath__64__39;
    sc_int<2> inst_mult_d_cellmath__64__38;
    sc_uint<11> inst_mult_d_cellmath__64__40;
    sc_uint<14> inst_mult_d_cellmath__64__37;
    sc_int<2> inst_mult_d_cellmath__64__44;
    sc_int<2> inst_mult_d_cellmath__64__43;
    sc_uint<10> inst_mult_d_cellmath__64__45;
    sc_uint<13> inst_mult_d_cellmath__64__42;
    sc_int<2> inst_mult_d_cellmath__64__49;
    sc_int<2> inst_mult_d_cellmath__64__48;
    sc_uint<9> inst_mult_d_cellmath__64__50;
    sc_uint<12> inst_mult_d_cellmath__64__47;
    sc_int<2> inst_mult_d_cellmath__64__54;
    sc_int<2> inst_mult_d_cellmath__64__53;
    sc_uint<8> inst_mult_d_cellmath__64__55;
    sc_uint<11> inst_mult_d_cellmath__64__52;
    sc_int<2> inst_mult_d_cellmath__64__59;
    sc_int<2> inst_mult_d_cellmath__64__58;
    sc_uint<7> inst_mult_d_cellmath__64__60;
    sc_uint<10> inst_mult_d_cellmath__64__57;
    sc_int<2> inst_mult_d_cellmath__64__64;
    sc_int<2> inst_mult_d_cellmath__64__63;
    sc_uint<6> inst_mult_d_cellmath__64__65;
    sc_uint<9> inst_mult_d_cellmath__64__62;
    sc_int<2> inst_mult_d_cellmath__64__69;
    sc_int<2> inst_mult_d_cellmath__64__68;
    sc_uint<5> inst_mult_d_cellmath__64__70;
    sc_uint<8> inst_mult_d_cellmath__64__67;
    sc_int<2> inst_mult_d_cellmath__64__74;
    sc_int<2> inst_mult_d_cellmath__64__73;
    sc_uint<4> inst_mult_d_cellmath__64__75;
    sc_uint<7> inst_mult_d_cellmath__64__72;
    sc_int<2> inst_mult_d_cellmath__64__79;
    sc_int<2> inst_mult_d_cellmath__64__78;
    sc_uint<3> inst_mult_d_cellmath__64__80;
    sc_uint<6> inst_mult_d_cellmath__64__77;
    sc_int<2> inst_mult_d_cellmath__64__84;
    sc_int<2> inst_mult_d_cellmath__64__83;
    sc_uint<2> inst_mult_d_cellmath__64__85;
    sc_uint<5> inst_mult_d_cellmath__64__82;
    sc_int<2> inst_mult_d_cellmath__64__89;
    sc_int<2> inst_mult_d_cellmath__64__88;
    sc_uint<1> inst_mult_d_cellmath__64__90;
    sc_uint<4> inst_mult_d_cellmath__64__87;
    sc_int<2> inst_mult_d_cellmath__64__94;
    sc_int<2> inst_mult_d_cellmath__64__93;
    sc_uint<3> inst_mult_d_cellmath__64__92;
    sc_uint<1> inst_cellmath__74__103;
    sc_uint<1> inst_cellmath__74__106;
    sc_uint<1> inst_cellmath__74__105;
    sc_uint<9> inst_cellmath__32_0;
    sc_uint<2> inst_cellmath__33__23_0;
    sc_uint<3> inst_cellmath__29_0;
    sc_uint<56> inst_cellmath__59_0;
    sc_uint<7> tmp_0_23_17_;
};
#endif // !defined cynw_cm_float_rsq_E8_M23_INCLUDED
    // !!!! amethyst/writers/SystemCbeh.cpp:4142
// cynw_cm_float_rsq - cynth invocation function


inline void cynw_cm_float_rsq_E8_M23( // module cynw_cm_float_rsq_E8_M23
    const sc_uint<1>& a_sign // input  a_sign : unsigned
    ,const sc_uint<8>& a_exp // input  a_exp[7:0] : unsigned
    ,const sc_uint<23>& a_man // input  a_man[22:0] : unsigned
    ,sc_uint<32>& x // output  x[31:0] : unsigned
)
{
    static class_cynw_cm_float_rsq_E8_M23 target; // BDW_REPLACE_NAME
    target(
        a_sign,
        a_exp,
        a_man,
        x    
);
}

/* CADENCE  vrHySgHarA== : u9/ySgnatBlWxVHRUQke6Og= ** DO NOT EDIT THIS LINE **/


