function calibData = readCalibDataFromEepromFile(binFileName)
% readCalibDataFromEepromFile
%   Retrieves calibration data of all algo tables from EEPROM BIN file.

fid = fopen(binFileName, 'rb');
binDataAll = fread(fid, Inf, '*uint8');
fclose(fid);

tableInfo = {'Algo_Calibration_Info_CalibInfo', '1200', '200';...
             'Algo_rtdOverAngX_CalibInfo', 'D00', '80';...
             'Algo_Thermal_Loop_CalibInfo', '1600', '1F0';...
             'Algo_Thermal_Loop_Extra_CalibInfo', 'B00', '70';...
             'CBUF_Calibration_Info_CalibInfo', '1A00', '200';...
             'DEST_txPWRpd_Info_CalibInfo', '1800', '11C';...
             'DIGG_Gamma_Info_CalibInfo', '1E00', 'D4';...
             'DIGG_Undist_Info_1_CalibInfo', '2000', '1000';...
             'DIGG_Undist_Info_2_CalibInfo', '3000', '1000';...
             'Dynamic_Range_Info_CalibInfo', '900', '100';...
             %'FRMW_tmpTrans_Info', 'XXXXXXXX', 'C30';... %TODO: complete
             'MEMS_Electro_Optics_Calibration_Info_CalibInfo', '380', '80';...
             'RGB_Calibration_Info_CalibInfo', '580', '80';...
             'RGB_Thermal_Info_CalibInfo', '1000', '1E8'};

headerSize = 16;
for iTable = 1:size(tableInfo, 1)
    calibData(iTable).tableName = tableInfo{iTable,1};
    tableOffset = hex2dec(tableInfo{iTable,2});
    tableSize = hex2dec(tableInfo{iTable,3})-headerSize;
    binData = binDataAll(tableOffset + headerSize + (1:tableSize));
    calibData(iTable).tableData = Calibration.tables.convertBinTableToCalibData(binData, calibData(iTable).tableName);
    
end

