function calibRaw = calibAndCostToRaw(params, cost)

K = params.Krgb;
R = params.Rrgb';
T = params.Trgb;

%calibRaw = [K(1,1) K(2,2) K(1,3) K(2,3) ...     
calibRaw = [K(1,1) K(1,2) K(1,3) ...
    K(2,1) K(2,2) K(2,3) ...
    K(3,1) K(3,2) K(3,3) ...     
R(:)' ...
T(:)' ...
cost];

end