function saveDSMParamsRaw(outputBinFilesPath, binWithHeaders, acDataBin, calibDataBin, dsmRegs)

DSM_params = [binWithHeaders ...
            acDataBin ...
            calibDataBin ...
            dsmRegs.dsmYoffset ... 
            dsmRegs.dsmXoffset ... 
            dsmRegs.dsmYscale ... 
            dsmRegs.dsmXscale ... 
    ];
 
mkdirSafe(outputBinFilesPath);
fullname = fullfile(outputBinFilesPath,'DSM_params');
f = fopen(fullname,'w');
fwrite(f,(vec(DSM_params)),'uint8');
fclose(f);
end
