function [fitresult, gof,vcmdTrgtTemp] = createLinFit(tempDegC, vCmd,targetTemp)
%CREATEFIT(TEMPDEGC,VCMD)
%  Create a fit.
%
%  Data for fit:
%      X Input : tempDegC
%      Y Output: vCmd
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%  Created by Itzahaki, Omer <omer.itzahaki@intel.com>
%  Auto-generated by MATLAB on 12-Dec-2019 11:11:40


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( tempDegC, vCmd );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );
vcmdTrgtTemp = fitresult(targetTemp);
end