function [ vPostTps ] = undistByTPSModel( v,tpsModel,runParams )
%UNDISTBYTPSMODEL applies the TPS model on x/z and y/z. Returns a
%normalized unit vecor. Assumes v to be an Nx3 XYZ vector. tpsModel should
%be generated by the function Calibration.Undist.createTpsUndistModel. 
% In case tpsModel is empty, we can load a saved model from
% runParams.outputFolder.
if isempty(tpsModel) && ~exist('runParams','var')
    vPostTps = v;
    return;
end
if isempty(tpsModel)
   load(fullfile(runParams.outputFolder,'AlgoInternal','tpsUndistModel.mat')); 
end

nPoints = size(v,1);
tanVec = (v(:,1:2)./v(:,3))';
postTpsTanVec = fnval(tpsModel,tanVec);
vPostTps =  [postTpsTanVec',ones(nPoints,1)];
vPostTps = normr(vPostTps);
end

