version = 1.0;
outputFolder = sprintf('\\\\ger\\ec\\proj\\ha\\RSG\\SA_3DCam\\Algorithm\\Releases\\IVCAM2.0\\MaxRange2Apd\\%4.2f\\',version);

if exist(outputFolder,'dir')
    answer = questdlg(sprintf('Version %4.2f Already exist, Override?',version), ...
        'Version Exists', ...
        'Yes','No','No');
    % Handle response
    switch answer
        case 'No'
            return;
    end
end
mkdirSafe(outputFolder);
cmd = sprintf([
    'mcc -m maxRange2Apd.m ' ...
    '-d  %s '...
    '-a ..\\..\\+Pipe\\tables\\* '...
    '-a ..\\..\\+Calibration\\targets\\* '...
    '-a ..\\..\\+Calibration\\initConfigCalib\\* '...
    '-a ..\\..\\+Calibration\\releaseConfigCalib\\* '...
    '-a ..\\..\\@HWinterface\\presetScripts\\* '...
    '-a ..\\..\\@HWinterface\\IVCam20Device\\* '...
    ],outputFolder);
eval(cmd);
copyfile('maxRangeToVapdConfig.xml',outputFolder);
