%{
Steps for resleasing a new calibration gui:
1. Version - update in calibToolVersion()
2. Run the relevant section below.
%}

%%
outputFolder = sprintf('\\\\ger\\ec\\proj\\ha\\RSG\\SA_3DCam\\Algorithm\\Releases\\IVCAM2.0\\IV2calibTool\\%4.2f\\',calibToolVersion());
mkdirSafe(outputFolder);
cmd = sprintf([
    'mcc -m IV2calibTool.m ' ...
    '-d  %s '...
    '-a ..\\..\\+Pipe\\tables\\* '...
    '-a ..\\..\\+Calibration\\targets\\* '...
    '-a ..\\..\\+Calibration\\initScript\\* '...
    '-a ..\\..\\@HWinterface\\presetScripts\\* '...
    '-a ..\\..\\@HWinterface\\IVCam20Device\\* '...
    '-a .\\@Spark\\* '...
	],outputFolder);
eval(cmd);



copyfile('calibParams.xml',outputFolder);
fw = Pipe.loadFirmware('../../+Calibration/initScript');

verReg = typecast(uint8([ mod(calibToolVersion,1)*100 floor(calibToolVersion()) 0 0]),'uint32');
vreg= [verReg 0 0 0 0 verReg 0 0 ];
fw.setRegs('DIGGspare',vreg);
fw.writeFirmwareFiles(fullfile(outputFolder,'configFiles'));
% %%
% mcc -m IV2rgbCalibTool.m ...
%     -d  \\ger\ec\proj\ha\RSG\SA_3DCam\Algorithm\Releases\IVCAM2.0\IV2calibTool\1.06\ ...
%     -a ..\..\+Pipe\tables\* ...
%     -a .\@ADB\*...
%     -a ..\..\+Calibration\initScript\*...
%     -a ..\..\@HWinterface\presetScripts\*...
%     -a ..\..\@HWinterface\IVCam20Device\*