%{
Steps for resleasing a new calibration gui:
1. Version - 
    a) In IV2CalibTool.m:6, update version. (for example, 1.05 -> 1.06).
            % Properties that correspond to app components
            properties (Access = public)
                VERSION = 1.06;
    b) In current file, update output path to the current version. 
    c) Make the output dir. 
            \\ger\ec\proj\ha\RSG\SA_3DCam\Algorithm\Releases\IVCAM2.0\IV2calibTool\1.06
2. Run the relevant section below or run the entire current script.
%}

%%
mcc -m IV2calibTool.m ...
    -d  \\ger\ec\proj\ha\RSG\SA_3DCam\Algorithm\Releases\IVCAM2.0\IV2calibTool\1.06\ ...
    -a ..\..\+Pipe\tables\* ...
    -a ..\..\+Calibration\targets\*...
    -a ..\..\+Calibration\calibParams\calibParams.xml...
    -a ..\..\+Calibration\initScript\*...
    -a ..\..\@HWinterface\presetScripts\*...
    -a ..\..\@HWinterface\IVCam20Device\*
%%
mcc -m IV2rgbCalibTool.m ...
    -d  \\ger\ec\proj\ha\RSG\SA_3DCam\Algorithm\Releases\IVCAM2.0\IV2calibTool\1.06\ ...
    -a ..\..\+Pipe\tables\* ...
    -a .\@ADB\*...
    -a ..\..\+Calibration\initScript\*...
    -a ..\..\@HWinterface\presetScripts\*...
    -a ..\..\@HWinterface\IVCam20Device\*