% This function iterates over the mat files generated by the function
% 'generateTemplateDataAllIR.m'
% It splits them to bins by their psnr.
function [] = splitDataToPsnrBins(rangeFinderMatDir)
% rangeFinderMatDir = 'X:\Data\IvCam2\NN\DCOR\IRFullRange8GTmp';
dir_list = dir(rangeFinderMatDir);
dir_list = dir_list(3:end); % Removes the files '.' and '..'
for i = 1:numel(dir_list)
    dir_st = dir_list(i);
    if dir_st.isdir
       continue 
    end
    fprintf('Processing file %s.\n',dir_st.name)
    fullFilePath = fullfile(rangeFinderMatDir,dir_st.name);
    load(fullFilePath);
    psnr = example.psnr;
    if psnr < 10
        psnrDir = fullfile(rangeFinderMatDir,['psnr_0', num2str(psnr)]);
    else
        psnrDir = fullfile(rangeFinderMatDir,['psnr_', num2str(psnr)]);
    end
    % Create the dir if it doesn't exist
    if 7~=exist(psnrDir,'dir')
        mkdir(psnrDir) 
    end
    movefile(fullFilePath,fullfile(psnrDir,dir_st.name))
    
    
    z(i) = example.z;
    p(i) = psnr;
    ir(i) = example.irMean;
    
end
figure
subplot(1,2,1)
plot(z,ir)
ylabel('IR')
xlabel('z(mm)')
subplot(1,2,2)
plot(z,p)
ylabel('PSNR')
xlabel('z(mm)')

end

